PATH=$(CMTROOT)/$(CMTBIN):.:/usr/local/bin:/nfs/farm/g/glast/u05/gcc-2.95.3/bin:/u1/local/mozilla:/u1/local/test/qt-x11-free-3.1.2/bin:/u1/jchiang/root/bin:/u1/jchiang/bin:/u1/jchiang/OpenOffice.org1.0.2:/u1/local/bin:/u1/jchiang/local/bin:/u/gl/jchiang/bin:.:/usr/local/bin:/nfs/farm/g/glast/u05/gcc-2.95.3/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/etc:/usr/X11R6/bin:/afs/slac.stanford.edu/g/glast/applications/install/@sys/usr/bin:/afs/slac.stanford.edu/g/glast/ground/releases:/afs/slac.stanford.edu/g/glast/ground/scripts:/afs/slac.stanford.edu/g/glast/ground/scripts/ReleaseManager:/afs/slac.stanford.edu/i386_linux24/usr/local/bin:/afs/slac.stanford.edu/g/glast/applications/install/@sys/usr/bin:/afs/slac.stanford.edu/g/glast/ground/releases:/afs/slac.stanford.edu/g/glast/ground/scripts:/afs/slac.stanford.edu/g/glast/ground/scripts/ReleaseManager:/afs/slac.stanford.edu/i386_linux24/usr/local/bin::$(ROOTSYS)/bin
CLASSPATH=$(CMTROOT)/java
debug_option=-g
cdebugflags=$(debug_option)
pp_cflags=-Di586
ccomp=$(cc) -c $(includes) $(cdebugflags) $(cflags) $(pp_cflags)
clink=$(cc) $(clinkflags)
ppcmd=-I
cpp=g++-2.95.3
cppdebugflags=$(debug_option)
cppflags=-w -pipe -ansi -W -Wall  -fPIC -shared -D_GNU_SOURCE -Dlinux -Dunix 
pp_cppflags=-D_GNU_SOURCE
cppcomp=$(cpp) -c $(includes) $(cppoptions) $(cppflags) $(pp_cppflags)
cpplinkflags=-Wl,-Bdynamic $(makeLinkMap) $(linkdebug)
cpplink=$(cpp)   $(cpplinkflags)
for=g77
fflags=$(debug_option)
fcomp=$(for) -c $(fincludes) $(fflags) $(pp_fflags)
flink=$(for) $(flinkflags)
javacomp=javac
javacopy=cp
jar=jar
X11_cflags=-I/usr/include
Xm_cflags=-I/usr/include
X_linkopts=-L/usr/X11R6/lib -lXm -lXt -lXext -lX11 -lm
lex=lex $(lexflags)
yaccflags= -l -d 
yacc=yacc $(yaccflags)
ar=ar r
ranlib=ranlib
make_shlib=$(CMTROOT)/mgr/cmt_make_shlib_common.sh extract
shlibsuffix=so
shlibbuilder=g++-2.95.3
shlibflags=-shared
symlink=/bin/ln -fs 
symunlink=/bin/rm -f 
build_library_links=$(cmtexe) build library_links -quiet -tag=$(tags)
remove_library_links=$(cmtexe) remove library_links -quiet -tag=$(tags)
cmtexe=$(CMTROOT)/$(CMTBIN)/cmt.exe
tags=$(CMTEXTRATAGS)
build_prototype=$(cmtexe) build prototype
build_dependencies=$(cmtexe) -quiet -tag=$(tags) build dependencies
build_triggers=$(cmtexe) build triggers
implied_library_prefix=-l
SHELL=/bin/sh
src=../src/
doc=../doc/
inc=../src/
mgr=../cmt/
application_suffix=.exe
library_prefix=lib
lock_command=chmod -R a-w ../*
unlock_command=chmod -R g+w ../*
MAKEFLAGS= --no-print-directory 
gmake_hosts=lx1 rsplus lxtest as7 dxplus ax7 hp2 aleph hp1 hpplus papou1-fe atlas
make_hosts=virgo-control1 rio0a vmpc38a
everywhere=hosts
install_command=cp 
uninstall_command=/bin/rm -f 
mkdir=mkdir
BINDIR=rh72_gcc2953
cppoptions=$(cppdebugflags_s)
cppdebugflags_s=-g
cppoptimized_s=-O2
cppprofiled_s=-pg
linkdebug=-g 
makeLinkMap=-Wl,-Map,Linux.map
componentshr_linkopts=-fPIC  -ldl 
libraryshr_linkopts=-fPIC -ldl 
GlastMain=$(GLASTPOLICYROOT)/src/GlastMain.cxx
TestGlastMain=$(GLASTPOLICYROOT)/src/TestGlastMain.cxx
pil_native_version=1.8.8
PIL_DIR=$(GLAST_EXT)/pil/$(pil_native_version)
pil_linkopts=-L $(PIL_DIR)/lib/linux-2.95.3 -lpil -ltermcap -lreadline
hoops_linkopts=-L$(hoopsDir) -lhoops 
PLATARCHdef=rh61_gcc2952
PLATARCH=rh72_gcc2953
EXTPACK_DIR=$(GLAST_EXT)
ROOT_DIR=$(EXTPACK_DIR)/ROOT
PYTHON_DIR=$(EXTPACK_DIR)/Python
XERCES_DIR=$(EXTPACK_DIR)/Xerces-C
BOOST_DIR=$(EXTPACK_DIR)/Boost
AIDA_DIR=$(EXTPACK_DIR)/AIDA
CLHEP_DIR=$(EXTPACK_DIR)/CLHEP
HTL_DIR=$(EXTPACK_DIR)/HTL
NAGC_DIR=$(EXTPACK_DIR)/Nag_C
GSL_DIR=$(EXTPACK_DIR)/GSL
GEANT4_DIR=$(EXTPACK_DIR)/geant4
MYSQL_DIR=$(EXTPACK_DIR)/MYSQL
ROOT_native_version=v3.04.02
ROOT_PATH=$(ROOT_DIR)/$(ROOT_native_version)/root
ROOTSYS=/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/ROOT/v3.04.02/root
dict=../dict/
rootcint=rootcint
ROOT_libs=-L$(ROOT_PATH)/lib -lCore -lCint -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lPostscript -lMatrix -lPhysics -lpthread -lm -ldl -rdynamic  -lTreePlayer -lProof -lGX11 
ROOT_linkopts=$(ROOT_libs)
ROOT_cppflagsEx=$(ppcmd) "$(ROOT_PATH)/include" -DUSE_ROOT
LD_LIBRARY_PATH=/u1/jchiang/local/lib:/u1/local/test/qt-x11-free-3.1.2/lib:.:/u/gl/jchiang/lib:/u1/local/lib:/u1/jchiang/root/lib:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/xerces/1.7.0/lib:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/cfitsio/v2410/lib:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/xerces/1.7.0/lib:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/cfitsio/v2410/lib:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/cfitsio/v2410/lib:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/xerces/1.7.0/lib:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/cfitsio/v2410/lib:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/xerces/1.7.0/lib:/u1/jchiang/SciTools/dev/xml/v4r3p1/rh72_gcc2953:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/CLHEP/1.8.0.0/lib:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/cfitsio/v2410/lib:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/cfitsio/v2410/lib::/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/ROOT/v3.04.02/root/bin:/afs/slac.stanford.edu/g/glast/ground/externalPackages/rh72_gcc2953/ROOT/v3.04.02/root/lib
hoops_cppflags=-I ../src -g -pedantic 
test_hoopsstamps=hoops.stamp
test_hoops_primstamps=hoops_prim.stamp
test_hoops_parstamps=hoops_par.stamp
GlastPolicyDir=$(GLASTPOLICYROOT)/$(BINDIR)
RootPolicyDir=$(ROOTPOLICYROOT)/$(BINDIR)
hoopsDir=$(HOOPSROOT)/$(BINDIR)
tag=rh72_gcc2953
hoops_tag=$(tag)
HOOPSROOT=/u1/jchiang/SciTools/dev/hoops/v0
PACKAGE_ROOT=$(HOOPSROOT)
hoops_root=../../../hoops/v0
HOOPSVERSION=v0
srcdir=../src
bin=../$(hoops_tag)/
javabin=../classes/
mgrdir=cmt
version=v0
package=hoops
RootPolicy_tag=$(tag)
ROOTPOLICYROOT=/u1/jchiang/SciTools/dev/RootPolicy/v2r1p2
RootPolicy_root=../../../RootPolicy/v2r1p2
ROOTPOLICYVERSION=v2r1p2
GlastPolicy_tag=$(tag)
GLASTPOLICYROOT=/u1/jchiang/SciTools/dev/GlastPolicy/v5r3
GlastPolicy_root=../../../GlastPolicy/v5r3
GLASTPOLICYVERSION=v5r3
pil_tag=$(tag)
PILROOT=/u1/jchiang/SciTools/dev/IExternal/pil/v1r188p4
pil_root=../../../IExternal/pil/v1r188p4
PILVERSION=v1r188p4
ROOT_tag=$(tag)
ROOTROOT=/u1/jchiang/SciTools/dev/IExternal/ROOT/v2r30402p0
ROOT_root=../../../IExternal/ROOT/v2r30402p0
ROOTVERSION=v2r30402p0
ExternalLibs_tag=$(tag)
EXTERNALLIBSROOT=/u1/jchiang/SciTools/dev/IExternal/ExternalLibs/v4r0p3
ExternalLibs_root=../../../IExternal/ExternalLibs/v4r0p3
EXTERNALLIBSVERSION=v4r0p3
use_requirements=requirements $(CMTROOT)/mgr/requirements $(ROOTPOLICYROOT)/cmt/requirements $(GLASTPOLICYROOT)/cmt/requirements $(PILROOT)/cmt/requirements $(ROOTROOT)/cmt/requirements $(EXTERNALLIBSROOT)/cmt/requirements 
use_includes= $(ppcmd)"$(GLASTPOLICYROOT)" $(ppcmd)"$(PIL_DIR)/include" $(ppcmd)"$(ROOT_PATH)/include" 
use_fincludes= $(use_includes)
use_stamps= $(hoops_stamps)  $(RootPolicy_stamps)  $(GlastPolicy_stamps)  $(pil_stamps)  $(ROOT_stamps)  $(ExternalLibs_stamps) 
use_cflags=  $(hoops_cflags)  $(RootPolicy_cflags)  $(GlastPolicy_cflags)  $(pil_cflags)  $(ROOT_cflags)  $(ExternalLibs_cflags) 
use_pp_cflags=  $(hoops_pp_cflags)  $(RootPolicy_pp_cflags)  $(GlastPolicy_pp_cflags)  $(pil_pp_cflags)  $(ROOT_pp_cflags)  $(ExternalLibs_pp_cflags) 
use_cppflags=  $(hoops_cppflags)  $(RootPolicy_cppflags)  $(GlastPolicy_cppflags)  $(pil_cppflags)  $(ROOT_cppflags)  $(ExternalLibs_cppflags) 
use_pp_cppflags=  $(hoops_pp_cppflags)  $(RootPolicy_pp_cppflags)  $(GlastPolicy_pp_cppflags)  $(pil_pp_cppflags)  $(ROOT_pp_cppflags)  $(ExternalLibs_pp_cppflags) 
use_fflags=  $(hoops_fflags)  $(RootPolicy_fflags)  $(GlastPolicy_fflags)  $(pil_fflags)  $(ROOT_fflags)  $(ExternalLibs_fflags) 
use_pp_fflags=  $(hoops_pp_fflags)  $(RootPolicy_pp_fflags)  $(GlastPolicy_pp_fflags)  $(pil_pp_fflags)  $(ROOT_pp_fflags)  $(ExternalLibs_pp_fflags) 
use_linkopts=  $(hoops_linkopts)  $(RootPolicy_linkopts)  $(GlastPolicy_linkopts)  $(pil_linkopts)  $(ROOT_linkopts)  $(ExternalLibs_linkopts) 
use_libraries= $(RootPolicy_libraries)  $(GlastPolicy_libraries)  $(pil_libraries)  $(ROOT_libraries)  $(ExternalLibs_libraries) 
includes= $(ppcmd)"$(HOOPSROOT)" $(use_includes)
fincludes= $(includes)
hoops_use_linkopts=  $(hoops_linkopts)  $(RootPolicy_linkopts)  $(GlastPolicy_linkopts)  $(pil_linkopts)  $(ROOT_linkopts)  $(ExternalLibs_linkopts) 
test_hoops_use_linkopts=  $(hoops_linkopts)  $(RootPolicy_linkopts)  $(GlastPolicy_linkopts)  $(pil_linkopts)  $(ROOT_linkopts)  $(ExternalLibs_linkopts) 
test_hoops_prim_use_linkopts=  $(hoops_linkopts)  $(RootPolicy_linkopts)  $(GlastPolicy_linkopts)  $(pil_linkopts)  $(ROOT_linkopts)  $(ExternalLibs_linkopts) 
test_hoops_par_use_linkopts=  $(hoops_linkopts)  $(RootPolicy_linkopts)  $(GlastPolicy_linkopts)  $(pil_linkopts)  $(ROOT_linkopts)  $(ExternalLibs_linkopts) 
constituents= hoops test_hoops test_hoops_prim test_hoops_par 
all_constituents= $(constituents)
constituentsclean= test_hoops_parclean test_hoops_primclean test_hoopsclean hoopsclean 
all_constituentsclean= $(constituentsclean)
